# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20180316_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='photo1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='photo2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='photo3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
