# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20180318_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
