# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='hello', max_length=400),
            preserve_default=False,
        ),
    ]
